# Numpy Crash Course

In [182]:
import numpy as np 

In [183]:
np.__version__

'2.2.4'

In [184]:
import sys
sys.version

'3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]'

# Creating Array

In [185]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [186]:
type(my_list)

list

In [187]:
arr = np.array(my_list)

In [188]:
arr

array([0, 1, 2, 3, 4, 5])

In [189]:
type(arr)

numpy.ndarray

In [190]:
type(my_list)

list

In [191]:
np. # we learn important function

SyntaxError: invalid syntax (3980787790.py, line 1)

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.arange(3.0)

array([0., 1., 2.])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(20,10) # 1st arg < 2nd arg

array([], dtype=int64)

In [ ]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [ ]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [ ]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [ ]:
np.arange(30,20) # 1 st arg always be < then 2nd arg

array([], dtype=int64)

In [ ]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [ ]:
np.arange(10,10)

array([], dtype=int64)

In [ ]:
np.arange()

TypeError: arange() requires stop to be specified.

In [ ]:
np.arange(0,30,5) # 10-starting from 30-end point,5-stop count

array([ 0,  5, 10, 15, 20, 25])

In [ ]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [ ]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [ ]:
np.zeros(3) # parameter tunning

array([0., 0., 0.])

In [ ]:
np.zeros(5,dtype=int) # hyperparameter tunning

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [ ]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [ ]:
zero = np.zeros([2,2])
print(zero)

print('####')

print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [ ]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [ ]:
np.zeros((5,10)) # bydefaul large -- will give row & 2nd arg - columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1)) # Parameter tunning

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
print(np.zeros(n,dtype=int)) # hyperparameter tunning

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [ ]:
n

(6, 7)

In [ ]:
n1

(6, 8)

In [ ]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
n

(6, 7)

In [ ]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.ones((5,4),dtype=int) # by default 5 - rows & 4 - columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [ ]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [ ]:
np.three(2,3)

AttributeError: module 'numpy' has no attribute 'three'

In [ ]:
np.ones(2)

array([1., 1.])

In [ ]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones((6,10),dtype= int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
np.twos((2,4))

AttributeError: module 'numpy' has no attribute 'twos'

In [ ]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [ ]:
range(5)

range(0, 5)

In [ ]:
r = range(5)
r

range(0, 5)

In [ ]:
for i in r:
    print(i)

0
1
2
3
4


In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
range(1,10)

range(1, 10)

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
range(1,10)

range(1, 10)

In [ ]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list(range(1,10,3))

[1, 4, 7]

In [ ]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [ ]:
rand(3,2)

NameError: name 'rand' is not defined

In [ ]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [ ]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [ ]:
np.random.rand(2,4)

array([[0.15702013, 0.44927922, 0.36393671, 0.59438916],
       [0.21318753, 0.45346723, 0.52949052, 0.4341665 ]])

In [ ]:
np.random.randint(2,20) #2nd argument is exclusive

3

In [ ]:
np.random.randint(0,1)

0

In [ ]:
np.random.randint(10,20,5)

array([17, 19, 17, 19, 13], dtype=int32)

In [ ]:
np.random.randint(1,6,4)

array([5, 3, 4, 3], dtype=int32)

In [ ]:
np.random.rand(3)

array([0.5859755 , 0.03989021, 0.87780334])

In [ ]:
np.random.randint(1)

0

In [ ]:
np.random.randint(30,20,10)

ValueError: low >= high

In [ ]:
np.random.randint(-30,20,10)

array([ -8, -14, -29, -27,   2, -25,   3,   1, -26, -12], dtype=int32)

In [ ]:
np.random.randint(20,30,10)

array([28, 25, 24, 24, 23, 28, 21, 26, 23, 27], dtype=int32)

In [ ]:
np.random.randint(5,9) # get the value <=1 & >=5

6

In [ ]:
np.random.randint(19,21,3)

array([19, 20, 20], dtype=int32)

In [ ]:
np.random.randint(1,12,10)

array([ 5,  6,  5,  7, 11,  4,  6,  7,  5,  2], dtype=int32)

In [ ]:
np.random.randint(10,40,(10,10)) #generre the element 10 -30 with 4*4 mtri 

array([[13, 12, 13, 12, 24, 19, 29, 13, 29, 24],
       [19, 28, 18, 26, 32, 24, 22, 25, 38, 33],
       [37, 29, 19, 35, 37, 26, 39, 30, 19, 37],
       [31, 39, 26, 23, 29, 26, 22, 14, 31, 38],
       [13, 27, 39, 14, 20, 16, 39, 30, 19, 14],
       [16, 27, 29, 26, 30, 13, 34, 19, 21, 26],
       [23, 28, 28, 20, 19, 32, 17, 33, 19, 22],
       [13, 36, 15, 30, 18, 31, 37, 26, 35, 31],
       [17, 39, 21, 32, 36, 12, 18, 32, 35, 24],
       [29, 38, 21, 33, 10, 37, 22, 16, 14, 34]], dtype=int32)

In [ ]:
np.random.randint(1,100,(12,12))

array([[44, 54, 75,  9,  3,  2, 77, 10, 84, 14, 49, 11],
       [56, 74,  3, 51, 45, 93, 67, 27, 51, 95, 26, 57],
       [60, 86, 62, 64, 41, 98, 27, 23, 24, 17,  1, 40],
       [48, 43,  3, 54, 96,  1,  1, 45,  1, 28, 33, 71],
       [63, 79, 59, 32, 14, 63, 86, 49, 79, 39, 11, 71],
       [56, 26, 50, 32, 24, 37, 46,  7, 11,  5, 43, 81],
       [15, 38, 50, 91,  5, 51, 62, 44, 34, 23, 64, 25],
       [95, 27, 56, 77, 48,  2, 35, 10, 60, 37, 97, 45],
       [20, 37, 27, 74, 91, 10, 74, 96, 52,  3, 61, 82],
       [39, 82, 38, 40,  6, 97,  9,  6,  7, 38, 43,  2],
       [39, 81, 45, 48, 79, 65, 34, 64, 58,  6, 22, 81],
       [78, 22,  6, 42, 43, 35, 94, 21, 35, 56,  4, 67]], dtype=int32)

In [ ]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [ ]:
b = np.random.randint(10,20,(5,4))
b

array([[19, 16, 17, 14],
       [16, 16, 13, 17],
       [11, 10, 13, 14],
       [13, 14, 10, 16],
       [19, 15, 17, 18]], dtype=int32)

In [ ]:
type(b)

numpy.ndarray

In [ ]:
b

array([[19, 16, 17, 14],
       [16, 16, 13, 17],
       [11, 10, 13, 14],
       [13, 14, 10, 16],
       [19, 15, 17, 18]], dtype=int32)

In [ ]:
b[:]

array([[19, 16, 17, 14],
       [16, 16, 13, 17],
       [11, 10, 13, 14],
       [13, 14, 10, 16],
       [19, 15, 17, 18]], dtype=int32)

In [ ]:
b[1:3]

array([[16, 16, 13, 17],
       [11, 10, 13, 14]], dtype=int32)

In [ ]:
b

array([[19, 16, 17, 14],
       [16, 16, 13, 17],
       [11, 10, 13, 14],
       [13, 14, 10, 16],
       [19, 15, 17, 18]], dtype=int32)

In [ ]:
b[1,2]

np.int32(13)

In [ ]:
b

array([[19, 16, 17, 14],
       [16, 16, 13, 17],
       [11, 10, 13, 14],
       [13, 14, 10, 16],
       [19, 15, 17, 18]], dtype=int32)

In [ ]:
b[1,3]

np.int32(17)

In [ ]:
b[-1,-1]

np.int32(18)

In [ ]:
b

array([[19, 16, 17, 14],
       [16, 16, 13, 17],
       [11, 10, 13, 14],
       [13, 14, 10, 16],
       [19, 15, 17, 18]], dtype=int32)

In [ ]:
b[2:3]

array([[11, 10, 13, 14]], dtype=int32)

In [ ]:
b

array([[19, 16, 17, 14],
       [16, 16, 13, 17],
       [11, 10, 13, 14],
       [13, 14, 10, 16],
       [19, 15, 17, 18]], dtype=int32)

In [ ]:
b[0:-2]

array([[19, 16, 17, 14],
       [16, 16, 13, 17],
       [11, 10, 13, 14]], dtype=int32)

In [ ]:
b

array([[19, 16, 17, 14],
       [16, 16, 13, 17],
       [11, 10, 13, 14],
       [13, 14, 10, 16],
       [19, 15, 17, 18]], dtype=int32)

In [ ]:
b[0,2]

np.int32(17)

In [ ]:
b

array([[19, 16, 17, 14],
       [16, 16, 13, 17],
       [11, 10, 13, 14],
       [13, 14, 10, 16],
       [19, 15, 17, 18]], dtype=int32)

In [ ]:
b[-5,-3]

np.int32(16)

In [ ]:
b

array([[19, 16, 17, 14],
       [16, 16, 13, 17],
       [11, 10, 13, 14],
       [13, 14, 10, 16],
       [19, 15, 17, 18]], dtype=int32)

In [ ]:
b[-4,2]

np.int32(13)

In [ ]:
np.random.randint(10,20,(4,4))

array([[15, 19, 14, 14],
       [16, 18, 10, 13],
       [15, 13, 14, 12],
       [16, 15, 19, 18]], dtype=int32)

In [ ]:
b

array([[19, 16, 17, 14],
       [16, 16, 13, 17],
       [11, 10, 13, 14],
       [13, 14, 10, 16],
       [19, 15, 17, 18]], dtype=int32)

In [ ]:
b[-4,-2]

np.int32(13)

In [ ]:
b

array([[19, 16, 17, 14],
       [16, 16, 13, 17],
       [11, 10, 13, 14],
       [13, 14, 10, 16],
       [19, 15, 17, 18]], dtype=int32)

In [ ]:
b[-4:2]

array([[16, 16, 13, 17]], dtype=int32)

In [ ]:
b[:]

array([[19, 16, 17, 14],
       [16, 16, 13, 17],
       [11, 10, 13, 14],
       [13, 14, 10, 16],
       [19, 15, 17, 18]], dtype=int32)

# Operations

In [ ]:
a = np.random.randint(10,20,10)
a

array([16, 14, 18, 18, 15, 12, 10, 19, 18, 17], dtype=int32)

In [ ]:
id(a)

2223653368432

In [ ]:
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr2 =np. random.randint(0,100,(10,10))

In [ ]:
arr2

array([[15, 29, 66, 31, 72, 63, 91, 94, 56, 17],
       [34, 95, 49, 79, 81, 62, 20, 24, 53, 49],
       [63, 62, 36, 64, 71, 88, 40, 37, 53, 70],
       [42,  1, 23, 57, 37, 71,  9, 55, 61,  8],
       [58,  1, 32, 18, 38, 96, 67, 80, 52, 40],
       [29, 40, 14, 36, 31, 92, 67, 35, 10, 84],
       [60, 73,  9, 60, 88, 84,  2, 26, 72, 41],
       [98, 29, 20, 54, 30, 99, 87,  6, 62, 41],
       [98, 11,  7, 74, 56, 75,  6, 26, 62, 47],
       [67, 35, 33, 47, 38, 82, 36, 42, 90, 63]], dtype=int32)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr[:4]

array([0, 1, 2, 3])

In [ ]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr2[0:5]

array([[15, 29, 66, 31, 72, 63, 91, 94, 56, 17],
       [34, 95, 49, 79, 81, 62, 20, 24, 53, 49],
       [63, 62, 36, 64, 71, 88, 40, 37, 53, 70],
       [42,  1, 23, 57, 37, 71,  9, 55, 61,  8],
       [58,  1, 32, 18, 38, 96, 67, 80, 52, 40]], dtype=int32)

In [ ]:
arr2

array([[15, 29, 66, 31, 72, 63, 91, 94, 56, 17],
       [34, 95, 49, 79, 81, 62, 20, 24, 53, 49],
       [63, 62, 36, 64, 71, 88, 40, 37, 53, 70],
       [42,  1, 23, 57, 37, 71,  9, 55, 61,  8],
       [58,  1, 32, 18, 38, 96, 67, 80, 52, 40],
       [29, 40, 14, 36, 31, 92, 67, 35, 10, 84],
       [60, 73,  9, 60, 88, 84,  2, 26, 72, 41],
       [98, 29, 20, 54, 30, 99, 87,  6, 62, 41],
       [98, 11,  7, 74, 56, 75,  6, 26, 62, 47],
       [67, 35, 33, 47, 38, 82, 36, 42, 90, 63]], dtype=int32)

In [ ]:
arr2

array([[15, 29, 66, 31, 72, 63, 91, 94, 56, 17],
       [34, 95, 49, 79, 81, 62, 20, 24, 53, 49],
       [63, 62, 36, 64, 71, 88, 40, 37, 53, 70],
       [42,  1, 23, 57, 37, 71,  9, 55, 61,  8],
       [58,  1, 32, 18, 38, 96, 67, 80, 52, 40],
       [29, 40, 14, 36, 31, 92, 67, 35, 10, 84],
       [60, 73,  9, 60, 88, 84,  2, 26, 72, 41],
       [98, 29, 20, 54, 30, 99, 87,  6, 62, 41],
       [98, 11,  7, 74, 56, 75,  6, 26, 62, 47],
       [67, 35, 33, 47, 38, 82, 36, 42, 90, 63]], dtype=int32)

In [ ]:
arr2[1,4]

np.int32(81)

In [ ]:
arr2

array([[15, 29, 66, 31, 72, 63, 91, 94, 56, 17],
       [34, 95, 49, 79, 81, 62, 20, 24, 53, 49],
       [63, 62, 36, 64, 71, 88, 40, 37, 53, 70],
       [42,  1, 23, 57, 37, 71,  9, 55, 61,  8],
       [58,  1, 32, 18, 38, 96, 67, 80, 52, 40],
       [29, 40, 14, 36, 31, 92, 67, 35, 10, 84],
       [60, 73,  9, 60, 88, 84,  2, 26, 72, 41],
       [98, 29, 20, 54, 30, 99, 87,  6, 62, 41],
       [98, 11,  7, 74, 56, 75,  6, 26, 62, 47],
       [67, 35, 33, 47, 38, 82, 36, 42, 90, 63]], dtype=int32)

In [ ]:
arr2[-5,5]

np.int32(92)

In [ ]:
arr2[-5,-5]

np.int32(92)

In [ ]:
arr2

array([[15, 29, 66, 31, 72, 63, 91, 94, 56, 17],
       [34, 95, 49, 79, 81, 62, 20, 24, 53, 49],
       [63, 62, 36, 64, 71, 88, 40, 37, 53, 70],
       [42,  1, 23, 57, 37, 71,  9, 55, 61,  8],
       [58,  1, 32, 18, 38, 96, 67, 80, 52, 40],
       [29, 40, 14, 36, 31, 92, 67, 35, 10, 84],
       [60, 73,  9, 60, 88, 84,  2, 26, 72, 41],
       [98, 29, 20, 54, 30, 99, 87,  6, 62, 41],
       [98, 11,  7, 74, 56, 75,  6, 26, 62, 47],
       [67, 35, 33, 47, 38, 82, 36, 42, 90, 63]], dtype=int32)

In [ ]:
arr2[-1,-2]

np.int32(90)

In [ ]:
arr2

array([[15, 29, 66, 31, 72, 63, 91, 94, 56, 17],
       [34, 95, 49, 79, 81, 62, 20, 24, 53, 49],
       [63, 62, 36, 64, 71, 88, 40, 37, 53, 70],
       [42,  1, 23, 57, 37, 71,  9, 55, 61,  8],
       [58,  1, 32, 18, 38, 96, 67, 80, 52, 40],
       [29, 40, 14, 36, 31, 92, 67, 35, 10, 84],
       [60, 73,  9, 60, 88, 84,  2, 26, 72, 41],
       [98, 29, 20, 54, 30, 99, 87,  6, 62, 41],
       [98, 11,  7, 74, 56, 75,  6, 26, 62, 47],
       [67, 35, 33, 47, 38, 82, 36, 42, 90, 63]], dtype=int32)

In [ ]:
arr2[::-1]

array([[67, 35, 33, 47, 38, 82, 36, 42, 90, 63],
       [98, 11,  7, 74, 56, 75,  6, 26, 62, 47],
       [98, 29, 20, 54, 30, 99, 87,  6, 62, 41],
       [60, 73,  9, 60, 88, 84,  2, 26, 72, 41],
       [29, 40, 14, 36, 31, 92, 67, 35, 10, 84],
       [58,  1, 32, 18, 38, 96, 67, 80, 52, 40],
       [42,  1, 23, 57, 37, 71,  9, 55, 61,  8],
       [63, 62, 36, 64, 71, 88, 40, 37, 53, 70],
       [34, 95, 49, 79, 81, 62, 20, 24, 53, 49],
       [15, 29, 66, 31, 72, 63, 91, 94, 56, 17]], dtype=int32)

In [ ]:
arr2

array([[15, 29, 66, 31, 72, 63, 91, 94, 56, 17],
       [34, 95, 49, 79, 81, 62, 20, 24, 53, 49],
       [63, 62, 36, 64, 71, 88, 40, 37, 53, 70],
       [42,  1, 23, 57, 37, 71,  9, 55, 61,  8],
       [58,  1, 32, 18, 38, 96, 67, 80, 52, 40],
       [29, 40, 14, 36, 31, 92, 67, 35, 10, 84],
       [60, 73,  9, 60, 88, 84,  2, 26, 72, 41],
       [98, 29, 20, 54, 30, 99, 87,  6, 62, 41],
       [98, 11,  7, 74, 56, 75,  6, 26, 62, 47],
       [67, 35, 33, 47, 38, 82, 36, 42, 90, 63]], dtype=int32)

In [ ]:
arr2[::-2]

array([[67, 35, 33, 47, 38, 82, 36, 42, 90, 63],
       [98, 29, 20, 54, 30, 99, 87,  6, 62, 41],
       [29, 40, 14, 36, 31, 92, 67, 35, 10, 84],
       [42,  1, 23, 57, 37, 71,  9, 55, 61,  8],
       [34, 95, 49, 79, 81, 62, 20, 24, 53, 49]], dtype=int32)

In [ ]:
arr2

array([[15, 29, 66, 31, 72, 63, 91, 94, 56, 17],
       [34, 95, 49, 79, 81, 62, 20, 24, 53, 49],
       [63, 62, 36, 64, 71, 88, 40, 37, 53, 70],
       [42,  1, 23, 57, 37, 71,  9, 55, 61,  8],
       [58,  1, 32, 18, 38, 96, 67, 80, 52, 40],
       [29, 40, 14, 36, 31, 92, 67, 35, 10, 84],
       [60, 73,  9, 60, 88, 84,  2, 26, 72, 41],
       [98, 29, 20, 54, 30, 99, 87,  6, 62, 41],
       [98, 11,  7, 74, 56, 75,  6, 26, 62, 47],
       [67, 35, 33, 47, 38, 82, 36, 42, 90, 63]], dtype=int32)

In [ ]:
arr2[::-3]

array([[67, 35, 33, 47, 38, 82, 36, 42, 90, 63],
       [60, 73,  9, 60, 88, 84,  2, 26, 72, 41],
       [42,  1, 23, 57, 37, 71,  9, 55, 61,  8],
       [15, 29, 66, 31, 72, 63, 91, 94, 56, 17]], dtype=int32)

In [ ]:
arr2

array([[15, 29, 66, 31, 72, 63, 91, 94, 56, 17],
       [34, 95, 49, 79, 81, 62, 20, 24, 53, 49],
       [63, 62, 36, 64, 71, 88, 40, 37, 53, 70],
       [42,  1, 23, 57, 37, 71,  9, 55, 61,  8],
       [58,  1, 32, 18, 38, 96, 67, 80, 52, 40],
       [29, 40, 14, 36, 31, 92, 67, 35, 10, 84],
       [60, 73,  9, 60, 88, 84,  2, 26, 72, 41],
       [98, 29, 20, 54, 30, 99, 87,  6, 62, 41],
       [98, 11,  7, 74, 56, 75,  6, 26, 62, 47],
       [67, 35, 33, 47, 38, 82, 36, 42, 90, 63]], dtype=int32)

In [ ]:
arr2[:-3]

array([[15, 29, 66, 31, 72, 63, 91, 94, 56, 17],
       [34, 95, 49, 79, 81, 62, 20, 24, 53, 49],
       [63, 62, 36, 64, 71, 88, 40, 37, 53, 70],
       [42,  1, 23, 57, 37, 71,  9, 55, 61,  8],
       [58,  1, 32, 18, 38, 96, 67, 80, 52, 40],
       [29, 40, 14, 36, 31, 92, 67, 35, 10, 84],
       [60, 73,  9, 60, 88, 84,  2, 26, 72, 41]], dtype=int32)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr.max()

np.int64(5)

In [ ]:
arr.min()

np.int64(0)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr.mean()

np.float64(2.5)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [ ]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

np.float64(3.0)

# Without work on import* can you please find median, mode

In [ ]:
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [197]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
arr

array([0, 1, 2, 3, 4, 5])

In [198]:
arr.reshape(2,3,order='C') 

array([[0, 1, 2],
       [3, 4, 5]])

In [199]:
arr.reshape(2,3,order='F') # print element with fortran 

array([[0, 2, 4],
       [1, 3, 5]])

In [200]:
arr.reshape(2,3,order='A') # A almost give you c type output

array([[0, 1, 2],
       [3, 4, 5]])

In [201]:
arr

array([0, 1, 2, 3, 4, 5])

In [202]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [203]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [204]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [205]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [209]:
arr

array([0, 1, 2, 3, 4, 5])

In [210]:
arr.reshape(3,2)  

array([[0, 1],
       [2, 3],
       [4, 5]])

# Indexing

In [212]:
mat = np.arange(0,100).reshape(10,10) 

In [213]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [214]:
row = 4
col = 5

In [215]:
col

5

In [216]:
row

4

In [217]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [218]:
mat[row,col] 

np.int64(45)

In [219]:
mat[4,5] 

np.int64(45)

In [220]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [221]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [222]:
col = 6

In [223]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [224]:
mat[6] # befault it represent to rows

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [225]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [226]:
# With Slices
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [227]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [228]:
mat[row,:] 

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [229]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [230]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [231]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [232]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [233]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [234]:
row

4

In [235]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [236]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [237]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [238]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [239]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [240]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [241]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [242]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [243]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [244]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [245]:
row

4

In [246]:
col

6

In [247]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [248]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [249]:
mat[1,4]

np.int64(14)

In [250]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [251]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [252]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [253]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [254]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [255]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [256]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [257]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [258]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [259]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [260]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [261]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [262]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [263]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [264]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [265]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [266]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [267]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [269]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [270]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [271]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [272]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [273]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [274]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [275]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [276]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [277]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 -- it indicates only column parts


array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [278]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [279]:
mat[0,1]

np.int64(1)

In [280]:
mat[1,6]

np.int64(16)

In [281]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [282]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [283]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [284]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [285]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [286]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [287]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [288]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [289]:
mat[3,5]

np.int64(35)

In [290]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [291]:
mat[1:2,2:4] 

array([[12, 13]])

In [292]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [293]:
mat[2:3,2:3] 

array([[22]])

In [294]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [295]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [296]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [297]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [298]:
mat[2:3,4:5]

array([[24]])

# Masking

In [299]:
mat # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [300]:
id(mat)

2223657296560

In [301]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [302]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [303]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [304]:
mat > 50


array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [305]:
mat[mat==50] 

array([50])

In [306]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [307]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [308]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [309]:
a1 = mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [310]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [311]:
a2 = mat[mat>50] 
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [312]:
a3 = mat[mat<=50] 
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [313]:
a4 = mat[mat==50]
a4

array([50])

# python program to generat otp

In [314]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 4303


In [315]:
def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

good even
good even
good even


In [316]:
def wish():
    print('good even')
wish()

wish()

wish()

good even
good even
good even


In [317]:
list1=['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x00000205BC573840>


In [318]:
x = [1, 2, 3]
y = x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]
