  # NumPy: the absolute basics for beginners

#  Insta ling NumPy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


# How to import NumPy

In [2]:
import numpy as np

#  Reading the example code

In [3]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

#  What is an array?
 An array is a central data structure of the NumPy library. An array is a grid of values and it contains
 information about the raw data, how to locate an element, and how to interpret an element. It has a grid of
 elements that can be indexed in 
various ways. The elements are all of the same type, referred to as the
 array 
dtype
 .
 An array can be indexed by a tuple of nonnegative integers, by booleans, by another array, or by integers.
 The 
rank
 of the array is the number of dimensions. The 
shape
 of the array is a tuple of integers giving the
 size of the array along each dimension.
 One way we can initialize NumPy arrays is from Python lists, using nested lists for two- or higher
dimensional data.

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a[0])

1


In [5]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[0])

[1 2 3 4]


# How to create a basic array
  * This section covers np.array() , np.zeros() , np.ones() , np.empty() , np.arange() , np.linspace() , dtype 
  * To create a NumPy array, you can use the function np.arra() .

In [6]:
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [7]:
np.zeros(2)

array([0., 0.])

In [8]:
np.ones(2)

array([1., 1.])

In [9]:
# Create an empty array with 2 elements
np.empty(2)

array([1., 1.])

In [10]:
np.arange(4)

array([0, 1, 2, 3])

In [11]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [12]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
x = np.ones(2,dtype=np.int64)
x

array([1, 1])

# Adding, Removing and Sorting elements

In [14]:
arr = np.array([2,1,5,3,7,4,6,8]) # array of integers

In [15]:
np.sort(arr) # sorting the array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
np.argsort(arr) # indirect sort along a specified axis

array([1, 0, 3, 5, 2, 6, 4, 7])

In [17]:
np.lexsort(arr) # Which is indirect stable  sort on multiple keys

np.int64(0)

In [18]:
np.searchsorted(arr,3) # Which will indelements in a sorted array

np.int64(2)

In [19]:
np.partition(arr,3) # Which is a partialsort

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [21]:
np.concatenate((a, b))  # Concatenates two arrays along the first axis

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [23]:
np.concatenate((x,y))  # Concatenates two arrays along the first axis

array([[1, 2],
       [3, 4],
       [5, 6]])

# How do you know the shape and size of an array?

In [24]:
array_example = np.array([[[0,1,2,3],
                           [4,5,6,7]],
                          [[0,1,2,3],
                           [4,5,6,7]],
                          [[0,1,2,3],
                           [4,5,6,7]]])

In [25]:
array_example.ndim

3

In [26]:
array_example.size

24

In [27]:
array_example.shape

(3, 2, 4)

# can you reshape an array?

In [28]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [29]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [30]:
np.reshape(a,newshape=(1,6),order='c')

C:\Users\Vaishnavi mane\AppData\Local\Temp\ipykernel_10084\1197333832.py:1: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  np.reshape(a,newshape=(1,6),order='c')


array([[0, 1, 2, 3, 4, 5]])

# How to convert a 1D array into 2D array 

In [31]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [32]:
a2 = a[np.newaxis,:]
a2.shape

(1, 6)

In [33]:
col_vector = a[:,np.newaxis]
col_vector.shape

(6, 1)

In [34]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [35]:
b = np.expand_dims(a,axis=1)
b.shape

(6, 1)

In [36]:
c = np.expand_dims(a,axis=0)
c.shape

(1, 6)

# Indexing and Slicing

In [37]:
data = np.array([1,2,3])
data[1]

np.int64(2)

In [38]:
data[0:2]

array([1, 2])

In [39]:
data[1:]

array([2, 3])

In [40]:
data[-2:]

array([2, 3])

In [41]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[a < 5])

[1 2 3 4]


In [42]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [43]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [44]:
c = a[(a>2) & (a<11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [45]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [46]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [47]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [48]:
list_of_coordinates = list(zip(b[0],b[1]))

In [49]:
for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [50]:
print(a[b])


[1 2 3 4]


In [51]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


#  How to create an array from existing data

In [52]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [53]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [54]:
a1 = np.array([[1,1],
               [2,2]])
a2 = np.array([[3,3],
               [4,4]])

In [55]:
np.vstack((a1,a2)) # Vertical stack of arrays

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [56]:
np.hstack((a1,a2)) # Horizontal stack of arrays

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [57]:
x = np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [58]:
np.hsplit(x,(3,4))


[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [59]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [60]:
b1 = a[0,:]
b1

array([1, 2, 3, 4])

In [61]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [62]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
b2 = a.copy()

# Basic array operations

In [64]:
data = np.array([1,2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [65]:
data - ones

array([0, 1])

In [66]:
data * ones

array([1, 2])

In [67]:
data / ones

array([1., 2.])

In [68]:
a = np.array([1,2,3,4])
a.sum()

np.int64(10)

In [69]:
b = np.array([[1,1],[2,2]])

In [70]:
b.sum(axis=0)

array([3, 3])

In [71]:
b.sum(axis=1)

array([2, 4])

#  Broadcasting

In [72]:
data = np.array([1.0,2.0])
data * 1.6

array([1.6, 3.2])

#  More useful array operations

In [73]:
data.max()

np.float64(2.0)

In [74]:
data.min()

np.float64(1.0)

In [75]:
data.sum()

np.float64(3.0)

In [76]:
a

array([1, 2, 3, 4])

In [77]:
a.sum()

np.int64(10)

In [78]:
a.min()

np.int64(1)

In [79]:
a.min(axis=0)

np.int64(1)

#  Creating matrices

In [80]:
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [81]:
data[0,1]

np.int64(2)

In [82]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [83]:
data[0:2,0]

array([1, 3])

In [84]:
data.max()

np.int64(6)

In [85]:
data.min()

np.int64(1)

In [86]:
data.sum()

np.int64(21)

In [87]:
data = np.array([[1,2],[5,3],[4,6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [88]:
data.max(axis=0)

array([5, 6])

In [89]:
data.max(axis=1)

array([2, 5, 6])

In [90]:
data = np.array([[1,2],[3,4]])
ones = np.array([[1,1],[1,1]])
data+ ones

array([[2, 3],
       [4, 5]])

In [91]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [92]:
np.ones(3)

array([1., 1., 1.])

In [93]:
np.zeros(3)

array([0., 0., 0.])

In [94]:
rng = np.random.default_rng()
rng.random(3)

array([0.26278042, 0.28176753, 0.07730936])

In [95]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [96]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [97]:
rng.random((3,2))

array([[0.95052485, 0.99514481],
       [0.04377544, 0.44976605],
       [0.51435838, 0.74103283]])

# Generating random numbers

In [98]:
rng.integers(5,size=(2,4))

array([[1, 4, 4, 2],
       [0, 3, 0, 3]])

#  How to get unique items and counts

In [99]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [100]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [101]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [102]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [103]:
 a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [104]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [105]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [106]:
unique_rows, indices, occurrence_count = np.unique(
a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [107]:
print(indices)

[0 1 2]


In [108]:
print(occurrence_count)

[2 1 1]


#  Transposing and reshaping a matrix

In [109]:
data

array([[1, 2],
       [3, 4]])

In [110]:
arr = np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [111]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [112]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

# How to reverse an array

In [113]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [114]:
reversed_arr = np.flip(arr)

In [115]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [116]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [117]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [118]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [119]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [120]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [121]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


#  Reshaping and flattening multidimensional arrays

In [122]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [123]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [124]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [125]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [126]:
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [127]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]


In [133]:
a= np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])